# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tree_data',
            fields=[
                ('tree_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tree_type', models.CharField(max_length=30)),
                ('tree_plant_time', models.DateTimeField(auto_now=True)),
                ('tree_loc_lat', models.CharField(max_length=15)),
                ('tree_loc_long', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user_auth',
            fields=[
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('user_loc_lat', models.CharField(max_length=15)),
                ('user_loc_long', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='tree_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='env.user_auth'),
        ),
    ]
