# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree_data',
            name='tree_last_watered',
            field=models.DateTimeField(null=True),
        ),
    ]
