# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0002_tree_data_tree_last_watered'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('event_loc_lat', models.CharField(max_length=15)),
                ('event_loc_long', models.CharField(max_length=15)),
                ('event_user_list', models.ManyToManyField(to='env.user_auth')),
            ],
        ),
    ]
