# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env', '0004_thanks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanks',
            name='thanks_from',
        ),
        migrations.AddField(
            model_name='thanks',
            name='thanks_from',
            field=models.ManyToManyField(related_name='thanks_from', to='env.user_auth'),
        ),
    ]
